# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0deba8d52af4347306c6ac16f7e8dd0db1f230e164f688286e35b0840d38bc3b874c996c97bd0936b3c1d34843781e203d5a8ab6ce9dcb661bafceaf417c456

test:
  secret_key_base: c982f2c32db9c12f55e29119785867af8d16d5e07de7c6b2fdd2d9c45712e06a8473d3348ca07a283b35b326ee5ed5b9f9f6a34a50c2dbb5feed102875ac77c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
